cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ROOT OR NOT IS_DIRECTORY "${ROOT}")
    message(FATAL_ERROR "ROOT must name a plugin qml directory")
endif()
get_filename_component(root_real "${ROOT}" REALPATH)

if(DEFINED INPUT)
    set(qml_files "${INPUT}")
else()
    file(GLOB_RECURSE qml_files LIST_DIRECTORIES FALSE "${ROOT}/*.qml")
endif()

set(allowed_modules QtQuick QtQuick.Controls.Basic QtQuick.Layouts
    QtQml QtCore QueMusic.PluginUI)

foreach(qml_file IN LISTS qml_files)
    if(NOT EXISTS "${qml_file}")
        message(FATAL_ERROR "Missing QML file: ${qml_file}")
    endif()
    get_filename_component(qml_real "${qml_file}" REALPATH)
    string(FIND "${qml_real}" "${root_real}/" root_pos)
    if(NOT root_pos EQUAL 0)
        message(FATAL_ERROR "QML file escapes ROOT: ${qml_file}")
    endif()
    file(STRINGS "${qml_file}" lines)
    set(line_number 0)
    foreach(line IN LISTS lines)
        math(EXPR line_number "${line_number} + 1")
        if(NOT line MATCHES "^[ \t]*import[ \t]+")
            continue()
        endif()
        string(REGEX MATCH "^[ \t]*import[ \t]+([^ \t;]+)" matched "${line}")
        set(uri "${CMAKE_MATCH_1}")
        set(accepted FALSE)
        if(uri MATCHES "^\".*\"$")
            string(REGEX REPLACE "^\"|\"$" "" relative "${uri}")
            if(NOT relative MATCHES "^(\/|[A-Za-z]:|[^/]+://)"
                    AND NOT relative MATCHES "\\\\")
                get_filename_component(file_dir "${qml_real}" DIRECTORY)
                if(EXISTS "${file_dir}/${relative}")
                    get_filename_component(import_real "${file_dir}/${relative}" REALPATH)
                    string(FIND "${import_real}" "${root_real}/" import_pos)
                    if(import_pos EQUAL 0 OR import_real STREQUAL root_real)
                        set(accepted TRUE)
                    endif()
                endif()
            endif()
        elseif(uri IN_LIST allowed_modules)
            set(accepted TRUE)
            if(uri STREQUAL "QueMusic.PluginUI")
                string(REGEX MATCH "^[ \t]*import[ \t]+QueMusic\\.PluginUI[ \t]+([^ \t;]+)" version_match "${line}")
                if(NOT CMAKE_MATCH_1 MATCHES "^1\\.[0-9]+$")
                    set(accepted FALSE)
                endif()
            endif()
        endif()
        if(NOT accepted)
            message(FATAL_ERROR "${qml_file}:${line_number}: rejected import ${uri}")
        endif()
    endforeach()
endforeach()
