if(NOT APPLE)
    message(FATAL_ERROR "This check requires macOS")
endif()
if(NOT DEFINED app_path OR NOT IS_DIRECTORY "${app_path}")
    message(FATAL_ERROR "App bundle is missing: ${app_path}")
endif()
if(NOT DEFINED library_name OR library_name STREQUAL "")
    message(FATAL_ERROR "Local module filename is required")
endif()

if(DEFINED deploy_tool)
    if(NOT EXISTS "${deploy_tool}" OR NOT DEFINED work_root OR work_root STREQUAL "")
        message(FATAL_ERROR "Relocation check needs macdeployqt and a temporary work root")
    endif()
    string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef unique_suffix)
    set(check_root "${work_root}-${unique_suffix}")
    file(MAKE_DIRECTORY "${check_root}")
    file(COPY "${app_path}" DESTINATION "${check_root}")
    get_filename_component(app_name "${app_path}" NAME)
    set(app_path "${check_root}/${app_name}")
    execute_process(COMMAND "${deploy_tool}" "${app_path}"
        RESULT_VARIABLE deploy_result OUTPUT_VARIABLE deploy_output ERROR_VARIABLE deploy_error)
    if(NOT deploy_result EQUAL 0)
        message(FATAL_ERROR "macdeployqt failed: ${deploy_output}\n${deploy_error}")
    endif()
endif()

set(package_root "${app_path}/Contents/PlugIns/quemusic")
set(module_path "${package_root}/local/${library_name}")
foreach(required_path IN ITEMS
        "${package_root}/local/manifest.json"
        "${module_path}"
        "${app_path}/Contents/Frameworks/QtCore.framework")
    if(NOT EXISTS "${required_path}")
        message(FATAL_ERROR "Deployed Local bundle is incomplete: ${required_path}")
    endif()
endforeach()
file(GLOB content_libraries
    "${app_path}/Contents/Frameworks/libquemusic_source_content_events*.dylib")
if(NOT content_libraries)
    message(FATAL_ERROR "Deployed Local bundle is missing source content events")
endif()

execute_process(COMMAND otool -l "${module_path}"
    RESULT_VARIABLE load_result OUTPUT_VARIABLE load_commands ERROR_VARIABLE load_error)
if(NOT load_result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect Local module rpaths: ${load_error}")
endif()
string(REGEX MATCHALL "path [^\n]+ \\(offset [0-9]+\\)" rpath_lines "${load_commands}")
set(has_bundle_rpath FALSE)
foreach(rpath_line IN LISTS rpath_lines)
    if(rpath_line MATCHES "path @loader_path/../../../Frameworks ")
        set(has_bundle_rpath TRUE)
    endif()
    if(rpath_line MATCHES "path /[^ ]+")
        message(FATAL_ERROR "Deployed Local module has an absolute rpath: ${rpath_line}")
    endif()
endforeach()
if(NOT has_bundle_rpath)
    message(FATAL_ERROR "Deployed Local module cannot resolve bundled frameworks")
endif()

execute_process(COMMAND otool -L "${module_path}"
    RESULT_VARIABLE link_result OUTPUT_VARIABLE linked_libraries ERROR_VARIABLE link_error)
if(NOT link_result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect Local module dependencies: ${link_error}")
endif()
string(REGEX MATCHALL "\n[ \t]+/[^ \t\n]+" absolute_links "${linked_libraries}")
foreach(link IN LISTS absolute_links)
    string(STRIP "${link}" link)
    if(NOT link MATCHES "^/(System/Library|usr/lib)/")
        message(FATAL_ERROR "Deployed Local module has a development-machine dependency: ${link}")
    endif()
endforeach()

if(DEFINED package_probe)
    if(NOT EXISTS "${package_probe}" OR NOT DEFINED check_root)
        message(FATAL_ERROR "Runtime probe requires a relocated bundle and probe executable")
    endif()
    set(isolated_root "${check_root}/isolated-plugins")
    file(MAKE_DIRECTORY "${isolated_root}")
    file(CREATE_LINK "${package_root}/local" "${isolated_root}/local" SYMBOLIC)
    execute_process(COMMAND "${package_probe}" "${isolated_root}" load
        RESULT_VARIABLE probe_result OUTPUT_VARIABLE probe_output ERROR_VARIABLE probe_error)
    if(NOT probe_result EQUAL 0)
        message(FATAL_ERROR "Relocated Local module failed to load: ${probe_output}\n${probe_error}")
    endif()
endif()

if(DEFINED check_root)
    file(REMOVE_RECURSE "${check_root}")
endif()
