foreach(required_variable build_dir package_probe library_name)
    if(NOT DEFINED ${required_variable} OR "${${required_variable}}" STREQUAL "")
        message(FATAL_ERROR "Missing required variable: ${required_variable}")
    endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)
set(prefix "${build_dir}/installed-local-package-${nonce}")
foreach(component PluginSdk LocalSource)
    set(command "${CMAKE_COMMAND}" --install "${build_dir}"
        --prefix "${prefix}" --component "${component}")
    if(DEFINED build_config AND NOT "${build_config}" STREQUAL "")
        list(APPEND command --config "${build_config}")
    endif()
    execute_process(COMMAND ${command} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${component} install failed:\n${output}\n${error}")
    endif()
endforeach()
set(package_root "${prefix}/lib/quemusic/plugins")
set(local_dir "${package_root}/local")
set(manifest "${local_dir}/manifest.json")
set(library "${local_dir}/${library_name}")
if(NOT EXISTS "${manifest}" OR NOT EXISTS "${library}")
    message(FATAL_ERROR "Installed Local package missing manifest or module")
endif()
execute_process(COMMAND "${package_probe}" "${package_root}" load
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Installed Local package load failed:\n${output}\n${error}")
endif()

file(READ "${manifest}" original_manifest)
string(REGEX REPLACE "\"qtMajor\": [0-9]+" "\"qtMajor\": 1"
    incompatible_manifest "${original_manifest}")
if(incompatible_manifest STREQUAL original_manifest)
    message(FATAL_ERROR "Could not create Qt-major mismatch fixture")
endif()
file(WRITE "${manifest}" "${incompatible_manifest}")
execute_process(COMMAND "${package_probe}" "${package_root}" reject
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Qt-major mismatch was not rejected:\n${output}\n${error}")
endif()
file(WRITE "${manifest}" "${original_manifest}")

string(REGEX REPLACE "\"buildKey\": \"[^\"]+\"" "\"buildKey\": \"InvalidBuildKey\""
    incompatible_manifest "${original_manifest}")
if(incompatible_manifest STREQUAL original_manifest)
    message(FATAL_ERROR "Could not create build-key mismatch fixture")
endif()
file(WRITE "${manifest}" "${incompatible_manifest}")
execute_process(COMMAND "${package_probe}" "${package_root}" reject
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Build-key mismatch was not rejected:\n${output}\n${error}")
endif()
file(WRITE "${manifest}" "${original_manifest}")

string(REGEX REPLACE "\"architecture\": \"[^\"]+\""
    "\"architecture\": \"mips64-unknown\""
    incompatible_manifest "${original_manifest}")
if(incompatible_manifest STREQUAL original_manifest)
    message(FATAL_ERROR "Could not create architecture mismatch fixture")
endif()
file(WRITE "${manifest}" "${incompatible_manifest}")
execute_process(COMMAND "${package_probe}" "${package_root}" reject-discovery
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Architecture mismatch was not rejected:\n${output}\n${error}")
endif()
file(WRITE "${manifest}" "${original_manifest}")

if(APPLE)
    file(GLOB event_libraries "${prefix}/lib/libquemusic_source_content_events*.dylib")
elseif(UNIX)
    file(GLOB event_libraries "${prefix}/lib/libquemusic_source_content_events*.so*")
else()
    file(GLOB event_libraries "${prefix}/bin/*quemusic_source_content_events*.dll"
        "${local_dir}/*quemusic_source_content_events*.dll")
endif()
if(NOT event_libraries)
    message(FATAL_ERROR "Installed content-events runtime is missing")
endif()
foreach(runtime IN LISTS event_libraries)
    file(RENAME "${runtime}" "${runtime}.hidden")
endforeach()
execute_process(COMMAND "${package_probe}" "${package_root}" missing-runtime
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Missing runtime dependency was not rejected:\n${output}\n${error}")
endif()
